### ISSUE TITLE
Technical review: Voyages in 3D

### ISSUE THREAD

**Issue by inactinique** [C2DH/jdh-notebook#148] opened 2024-02-19 11:16 UTC
pid: 52s3BFHa5Miy

**Comment by inactinique** [comment] 2024-02-19 11:16
(will try to do it later this week)

**Comment by eliselavy** [comment] 2024-02-27 13:30
duplicate of https://github.com/C2DH/jdh-notebook/issues/131

**Closed by eliselavy** 2024-02-27 13:30 UTC
